default_deploy_mode = "upload"

[upload]
auth_token = "YOURAUTHTOKENHERE"
branch = "default"
# username = "your username or email"
# password = "your password"
# ptr = false
# hostname = "screeps.com"
# ssl = true
# port = 443

[sim]
auth_token = "YOURAUTHTOKENHERE"
branch = "default"
# username = "your username or email"
# password = "your password"
# ptr = false
# hostname = "screeps.com"
# ssl = true
# port = 443

# [copy]
# # On Windows, use forward slashes instead of backslashes for the destination
# destination = "your copy destination"
# prune = false
# branch = "default"

# [build]
# use absolute file path to get out of "target/"
# ouptut_js_file = "main.js"
# output_wasm_file = "compiled.wasm"